# Generated by Django 4.0.4 on 2022-04-22 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_note'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
        migrations.AlterModelOptions(
            name='note',
            options={'verbose_name': 'Lead', 'verbose_name_plural': 'Leads'},
        ),
    ]
