# Generated by Django 4.0.3 on 2022-05-02 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_alter_note_options_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.FileField(default='No documents in existing rows', upload_to='documents', verbose_name='Fichier'),
        ),
    ]
