# Generated by Django 4.0.3 on 2022-04-15 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255, verbose_name='Entreprise')),
                ('contact_person', models.CharField(max_length=255, verbose_name='Contact')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=255, verbose_name='Téléphone')),
                ('website', models.CharField(blank=True, max_length=255, null=True, verbose_name='Site web')),
                ('confidence', models.IntegerField(blank=True, null=True)),
                ('estimated_value', models.IntegerField(blank=True, null=True, verbose_name='Valeur estimé')),
                ('status', models.CharField(choices=[('Nouveau', 'Nouveau'), ('Contacter', 'Contacter'), ('En cours', 'En cours'), ('Perdu', 'Perdu'), ('Gagner', 'Gagner')], default='Nouveau', max_length=25)),
                ('priority', models.CharField(choices=[('Faible', 'Faible'), ('Moyen', 'Moyen'), ('Fort', 'Fort')], default='Moyen', max_length=25, verbose_name='Priorité')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
