# Generated by Django 4.0.3 on 2022-04-15 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lead', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to=settings.AUTH_USER_MODEL, verbose_name='Créer par'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='priority',
            field=models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyen'), ('high', 'Fort')], default='medium', max_length=25, verbose_name='Priorité'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'Nouveau'), ('contacted', 'Contacter'), ('inprogress', 'En cours'), ('lost', 'Perdu'), ('won', 'Gagner')], default='new', max_length=25),
        ),
    ]
