# Generated by Django 4.0.3 on 2022-04-15 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0002_alter_lead_created_by_alter_lead_priority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('Nouveau', 'Nouveau'), ('Contacter', 'Contacter'), ('En cours', 'En cours'), ('Perdu', 'Perdu'), ('Gagner', 'Gagner')], default='Nouveau', max_length=25),
        ),
    ]
