# Generated by Django 4.0.3 on 2022-04-15 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0003_alter_lead_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='priority',
            field=models.CharField(choices=[('Faible', 'Faible'), ('Moyenne', 'Moyenne'), ('Forte', 'Forte')], default='Moyenne', max_length=25, verbose_name='Priorité'),
        ),
    ]
